Web/Controllers/HomeController.cs
using Arquitetura.Controller;
using Core.Business.Account;
using Core.Business.Equipes;
using Core.Business.Eventos;
using Core.Business.Lancamento;
using Core.Business.Participantes;
using Core.Business.Reunioes;
using SysIgreja.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Utils.Constants;
using Utils.Enums;
using Utils.Extensions;
using Utils.Services;

namespace SysIgreja.Controllers
{

    [Authorize]
    public class HomeController : SysIgrejaControllerBase
    {
        private readonly IEquipesBusiness equipesBusiness;
        private readonly IParticipantesBusiness participantesBusiness;
        private readonly ILancamentoBusiness lancamentoBusiness;
        private readonly IReunioesBusiness reunioesBusiness;
        private readonly IEventosBusiness eventosBusiness;
        private readonly IAccountBusiness accountBusiness;

        public HomeController(IEquipesBusiness equipesBusiness, IParticipantesBusiness participantesBusiness, ILancamentoBusiness lancamentoBusiness, IEventosBusiness eventosBusiness, IAccountBusiness accountBusiness, IReunioesBusiness reunioesBusiness) : base(eventosBusiness, accountBusiness)
        {
            this.lancamentoBusiness = lancamentoBusiness;
            this.participantesBusiness = participantesBusiness;
            this.equipesBusiness = equipesBusiness;
            this.eventosBusiness = eventosBusiness;
            this.accountBusiness = accountBusiness;
            this.reunioesBusiness = reunioesBusiness;
        }

        [Authorize(Roles = Usuario.Master + "," + Usuario.Admin + "," + Usuario.Secretaria)]
        public ActionResult Admin()
        {
            ViewBag.Title = "Sistema de Gestão";

            GetEventos();
            return View();
        }

        [HttpGet]
        public ActionResult GetResultadosAdmin(int EventoId)
        {
            var ReceberPix = lancamentoBusiness.GetPagamentosEvento(EventoId).Where(x => x.Tipo == TiposLancamentoEnum.Receber && x.MeioPagamento.Descricao == "PIX").Select(x => x.Valor).DefaultIfEmpty(0).Sum();
            var PagarPix = lancamentoBusiness.GetPagamentosEvento(EventoId).Where(x => x.Tipo == TiposLancamentoEnum.Pagar && x.MeioPagamento.Descricao == "PIX").Select(x => x.Valor).DefaultIfEmpty(0).Sum();
            var SaldoPix = ReceberPix - PagarPix;
            var ReceberDinheiro = lancamentoBusiness.GetPagamentosEvento(EventoId).Where(x => x.Tipo == TiposLancamentoEnum.Receber && x.MeioPagamento.Descricao == "Dinheiro").Select(x => x.Valor).DefaultIfEmpty(0).Sum();
            var PagarDinheiro = lancamentoBusiness.GetPagamentosEvento(EventoId).Where(x => x.Tipo == TiposLancamentoEnum.Pagar && x.MeioPagamento.Descricao == "Dinheiro").Select(x => x.Valor).DefaultIfEmpty(0).Sum();
            var SaldoDinheiro = ReceberDinheiro - PagarDinheiro;
            var TotalReceber = lancamentoBusiness.GetPagamentosEvento(EventoId).Where(x => x.Tipo == TiposLancamentoEnum.Receber).Select(x => x.Valor).DefaultIfEmpty(0).Sum();
            var TotalPagar = lancamentoBusiness.GetPagamentosEvento(EventoId).Where(x => x.Tipo == TiposLancamentoEnum.Pagar).Select(x => x.Valor).DefaultIfEmpty(0).Sum();
            var SaldoGeral = TotalReceber - TotalPagar;
            var result = new
            {
                Evento = eventosBusiness.GetEventoById(EventoId).Status.GetDescription(),
                Confirmados = participantesBusiness.GetParticipantesByEvento(EventoId).Where(x => x.Status == StatusEnum.Confirmado).Count(),
                Cancelados = participantesBusiness.GetParticipantesByEvento(EventoId).Where(x => x.Status == StatusEnum.Cancelado).Count(),
                Espera = participantesBusiness.GetParticipantesByEvento(EventoId).Where(x => x.Status == StatusEnum.Espera).Count(),
                Presentes = participantesBusiness.GetParticipantesByEvento(EventoId).Where(x => x.Checkin).Count(),
                Isencoes = lancamentoBusiness.GetPagamentosEvento(EventoId).ToList().Where(x => x.ParticipanteId != null && x.Tipo == TiposLancamentoEnum.Receber && x.MeioPagamento.Descricao == MeioPagamentoPadraoEnum.Isencao.GetDescription()).Count(),
                Total = participantesBusiness.GetParticipantesByEvento(EventoId).Where(x => x.Status != StatusEnum.Cancelado && x.Status != StatusEnum.Espera).Count(),
                Boletos = participantesBusiness.GetParticipantesByEvento(EventoId).Where(x => x.Boleto && !x.PendenciaBoleto).Count(),
                Contatos = participantesBusiness.GetParticipantesByEvento(EventoId).Where(x => !x.PendenciaContato).Count(),
                Meninos = participantesBusiness.GetParticipantesByEvento(EventoId).Where(x => x.Sexo == SexoEnum.Masculino && x.Status != StatusEnum.Cancelado && x.Status != StatusEnum.Espera).Count(),
                Meninas = participantesBusiness.GetParticipantesByEvento(EventoId).Where(x => x.Sexo == SexoEnum.Feminino && x.Status != StatusEnum.Cancelado && x.Status != StatusEnum.Espera).Count(),
                SaldoGeral = UtilServices.DecimalToMoeda(SaldoGeral),
                SaldoPix = UtilServices.DecimalToMoeda(SaldoPix),
                SaldoDinheir = UtilServices.DecimalToMoeda(SaldoDinheiro),
                TotalPagar = UtilServices.DecimalToMoeda(TotalPagar),
                TotalReceber = UtilServices.DecimalToMoeda(TotalReceber),
                UltimosInscritos = participantesBusiness.GetParticipantesByEvento(EventoId)
                .OrderByDescending(x => x.DataCadastro).Take(5).ToList().Select(x => new ParticipanteViewModel
                {
                    Nome = UtilServices.CapitalizarNome(x.Nome),
                    Sexo = x.Sexo.GetDescription(),
                    Idade = UtilServices.GetAge(x.DataNascimento)
                }).ToList(),
                EquipeMeninos = equipesBusiness.GetEquipantesEvento(EventoId).Where(x => x.Equipante.Sexo == SexoEnum.Masculino).Count(),
                EquipeMeninas = equipesBusiness.GetEquipantesEvento(EventoId).Where(x => x.Equipante.Sexo == SexoEnum.Feminino).Count(),
                Equipes = equipesBusiness.GetEquipes(EventoId).Select(x => new ListaEquipesViewModel
                {
                    Id = x.Id,
                    Equipe = x.Description,
                    QuantidadeMembros = equipesBusiness.GetMembrosEquipe(EventoId, (EquipesEnum)x.Id).Count()
                }).ToList(),
                Reunioes = reunioesBusiness.GetReunioes(EventoId).ToList().Select(x => new ReuniaoViewModel
                {
                    Id = x.Id,
                    DataReuniao = x.DataReuniao,
                    Presenca = x.Presenca.Count()
                }).ToList()
            };

            return Json(new { result }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult GetDetalhamentoEvento(int EventoId)
        {
            var result = new
            {
                Equipantes = equipesBusiness
                .GetEquipantesEvento(EventoId)
                .OrderBy(x => x.Equipe)
                .ThenBy(x => x.Tipo)
                .ThenBy(x => x.Equipante.Nome)
                .ToList()
                .Select(x => new
                {
                    Equipe = x.Equipe.GetDescription(),
                    Nome = x.Equipante.Nome,
                    Tipo = x.Tipo.GetDescription(),
                    Fone = x.Equipante.Fone
                })
            };


            return Json(new { result }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Coordenador()
        {
            ViewBag.Title = "Sistema de Gestão";
            int eventoId = (eventosBusiness.GetEventoAtivo() ?? eventosBusiness.GetEventos().OrderByDescending(x => x.DataEvento).First()).Id;
            var user = GetApplicationUser();
            var equipanteEvento = equipesBusiness.GetEquipanteEventoByUser(eventoId, user.Id);
            var membrosEquipe = equipesBusiness.GetMembrosEquipe(eventoId, equipanteEvento.Equipe);
            ViewBag.Equipante = equipanteEvento.Equipante;
            ViewBag.Equipe = equipanteEvento.Equipe.GetDescription();
            ViewBag.QtdMembros = membrosEquipe.Count();
            ViewBag.Reunioes = reunioesBusiness.GetReunioes(eventoId)
                .ToList()
                .OrderBy(x => DateTime.Now.AddHours(4).Subtract(x.DataReuniao).TotalDays < 0 ? DateTime.Now.AddHours(4).Subtract(x.DataReuniao).TotalDays * -1 : DateTime.Now.AddHours(4).Subtract(x.DataReuniao).TotalDays)
                .Select(x => new ReuniaoViewModel { DataReuniao = x.DataReuniao, Id = x.Id });
            ViewBag.Membros = membrosEquipe.ToList().Select(x => new EquipanteViewModel
            {
                Id = x.Equipante.Id,
                Sexo = x.Equipante.Sexo.GetDescription(),
                Fone = x.Equipante.Fone,
                Idade = UtilServices.GetAge(x.Equipante.DataNascimento),
                Nome = x.Equipante.Nome,
                Vacina = x.Equipante.HasVacina,
                Faltas = reunioesBusiness.GetFaltasByEquipanteId(x.EquipanteId, eventoId),
                Oferta = lancamentoBusiness.GetPagamentosEquipante(x.EquipanteId).Any()
            });

            return View();
        }

        [HttpGet]
        public ActionResult GetPresenca(int ReuniaoId)
        {
            var presenca = equipesBusiness.GetPresenca(ReuniaoId).Select(x => x.EquipanteEventoId).ToList();

            var user = GetApplicationUser();
            var eventoId = (eventosBusiness.GetEventoAtivo() ?? eventosBusiness.GetEventos().OrderByDescending(x => x.DataEvento).First()).Id;

            var result = equipesBusiness
                .GetMembrosEquipe(eventoId, equipesBusiness.GetEquipanteEventoByUser(eventoId, user.Id).Equipe).ToList().Select(x => new PresencaViewModel
                {
                    Id = x.Id,
                    Nome = x.Equipante.Nome,

Web/Controllers/ReuniaoController.cs
using Arquitetura.Controller;
using Core.Business.Account;
using Core.Business.Eventos;
using Core.Business.Reunioes;
using Core.Models.Reunioes;
using SysIgreja.ViewModels;
using System.Linq;
using System.Web.Mvc;
using Utils.Constants;
using Utils.Extensions;

namespace SysIgreja.Controllers
{

    [Authorize(Roles = Usuario.Master + "," + Usuario.Admin + "," + Usuario.Secretaria)]
    public class ReuniaoController : SysIgrejaControllerBase
    {
        private readonly IReunioesBusiness reuniaosBusiness;

        public ReuniaoController(IReunioesBusiness ReuniaosBusiness, IEventosBusiness eventosBusiness, IAccountBusiness accountBusiness) :base(eventosBusiness, accountBusiness)
        {
            this.reuniaosBusiness = ReuniaosBusiness;
        }

        public ActionResult Index()
        {
            ViewBag.Title = "Reuniões";
            GetEventos();

            return View();
        }

        [HttpPost]
        public ActionResult GetReunioes(int EventoId)
        {
            var result = reuniaosBusiness
                .GetReunioes(EventoId)
                .ToList()
                .Select(x => new ReuniaoViewModel
                {
                    Id = x.Id,
                    DataReuniao = x.DataReuniao,
                    Presenca = x.Presenca.Count()
                });

            return Json(new { data = result }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult GetReuniao(int Id)
        {
            var result = reuniaosBusiness.GetReuniaoById(Id);
            result.Presenca = null;

            return Json(new { Reuniao = result }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult PostReuniao(PostReuniaoModel model)
        {
            reuniaosBusiness.PostReuniao(model);

            return new HttpStatusCodeResult(200);
        }

        [HttpPost]
        public ActionResult DeleteReuniao(int Id)
        {
            reuniaosBusiness.DeleteReuniao(Id);

            return new HttpStatusCodeResult(200);
        }
    }
}

Web/Views/Home/Admin.cshtml
@using Microsoft.AspNet.Identity
@using Utils.Constants;
@{
    ViewBag.Numero = new Random().Next();
}

<div class="wrapper wrapper-content">
    <div class="row">
        <div class="col-lg-12 col-sm-12" style="padding:5px">
            <select class="form-control" id="eventoid" onchange="GetResultadosAdmin()">
                @foreach (var evento in ViewBag.Eventos)
                {
                    <option value="@evento.Id">@evento.TipoEvento @evento.Numeracao.ToString()</option>
                }
            </select>
        </div>
        <div class="col-lg-6 col-xs-12 p-w-xs">
            <div class="row vertical-align">
                <div class="pointer" style="width:100%;" onclick="window.location.href='@Url.Action("Index", "Participante")'">
                    <div class="col-xs-12 col-lg-4 p-w-xs">
                        <div class="width100 bloco widget blue-bg p-md text-center">
                            <div class="m-b-xs">
                                <i class="m-b-sm fa fa-users fa-3x"></i>
                                <h1 class="m-xs" id="total"></h1>

                                <small>Participantes</small>
                            </div>
                        </div>
                    </div>
                    <div class="col-xs-6 col-lg-4 p-w-xs">
                        <div class="width100 bloco widget navy-bg p-md text-center">
                            <div class="m-b-xs">
                                <i class="m-b-sm fa fa-check fa-3x"></i>
                                <h1 class="m-xs" id="confirmados"></h1>

                                <small>Confirmados</small>
                            </div>
                        </div>
                    </div>
                    <div class="col-xs-6 col-lg-4 p-w-xs">
                        <div class="width100 bloco widget black-bg p-md text-center">
                            <div class="m-b-xs">
                                <i class="m-b-sm fa fa-suitcase fa-3x"></i>
                                <h1 class="m-xs" id="presentes"></h1>

                                <small>Presentes</small>
                            </div>
                        </div>
                    </div>
                    <div class="col-xs-6 col-lg-3 p-w-xs">
                        <div class="width100 bloco widget red-bg p-md text-center">
                            <div class="m-b-xs">
                                <i class="m-b-sm fa fa-times fa-3x"></i>
                                <h1 class="m-xs" id="cancelados"></h1>

                                <small>Cancelados</small>
                            </div>
                        </div>
                    </div>
                    <div class="col-xs-6 col-lg-3 p-w-xs">
                        <div class="width100 bloco widget bg-warning p-md text-center">
                            <div class="m-b-xs">
                                <i class="m-b-sm fa fa-user-clock fa-3x"></i>
                                <h1 class="m-xs" id="espera"></h1>

                                <small>em Espera</small>
                            </div>
                        </div>
                    </div>
                    <div class="col-xs-6 col-lg-3 p-w-xs">
                        <div class="width100 bloco widget male p-lg text-center">
                            <div class="m-b-xs">
                                <i class="m-b-sm fa fa-male fa-3x male"></i>
                                <h1 class="m-xs" id="meninos"></h1>

                                <small>Homens</small>
                            </div>
                        </div>
                    </div>
                    <div class="col-xs-6 col-lg-3 p-w-xs">
                        <div class="width100 bloco widget female p-lg text-center">
                            <div class="m-b-xs">
                                <i class="m-b-sm fa fa-female fa-3x female"></i>
                                <h1 class="m-xs" id="meninas"></h1>

                                <small>Mulheres</small>
                            </div>
                        </div>
                    </div>
                </div>
                @*<div class="col-xs-6 col-lg-3 p-w-xs">
            <div class="width100 bloco widget yellow-bg p-md text-center">
                <div class="m-b-xs">
                    <i class="m-b-sm fa fa-barcode fa-3x"></i>
                    <h1 class="m-xs" id="boletos"></h1>

                    <small>Boletos Pendentes</small>
                </div>
            </div>
        </div>
        <div class="col-xs-6 col-lg-3 p-w-xs">
            <div class="width100 bloco widget lazur-bg p-md text-center">
                <div class="m-b-xs">
                    <i class="m-b-sm fab fa-whatsapp fa-3x"></i>
                    <h1 class="m-xs" id="contatos"></h1>

                    <small>Contatos Pendentes</small>
                </div>
            </div>
        </div>*@
                @if (User.IsInRole(Usuario.Admin) || User.IsInRole(Usuario.Master))
                {
                    <div class="col-xs-6 col-lg-6 p-w-xs pointer" onclick="window.location.href='@Url.Action("Index", "Lancamento")'">
                        <div class="width100 bloco widget red-bg p-md text-center">
                            <div class="m-b-xs">
                                <i class="m-b-sm far fa-money-bill-alt fa-3x"></i>
                                <h2 class="m-xs" id="despesa"></h2>

                                <small>Total Despesas</small>
                            </div>
                        </div>
                    </div>
                    <div class="col-xs-6 col-lg-6 p-w-xs pointer" onclick="window.location.href='@Url.Action("Index", "Lancamento")'">
                        <div class="width100 bloco widget navy-bg p-md text-center">
                            <div class="m-b-xs">
                                <i class="m-b-sm far fa-money-bill-alt fa-3x"></i>
                                <h2 class="m-xs" id="receita"></h2>

                                <small>Total Receita</small>
                            </div>
                        </div>
                    </div>
                    <div class="col-xs-4 col-lg-4 p-w-xs pointer" onclick="window.location.href='@Url.Action("Index", "Lancamento")'">
                        <div class="width100 bloco widget blue-bg p-md text-center">
                            <div class="m-b-xs">
                                <i class="m-b-sm far fa-money-bill-alt fa-3x"></i>
                                <h2 class="m-xs" id="saldopix"></h2>

                                <small>Saldo PIX</small>
                            </div>
                        </div>
                    </div>
                    <div class="col-xs-4 col-lg-4 p-w-xs pointer" onclick="window.location.href='@Url.Action("Index", "Lancamento")'">
                        <div class="width100 bloco widget blue-bg p-md text-center">
                            <div class="m-b-xs">
                                <i class="m-b-sm far fa-money-bill-alt fa-3x"></i>
                                <h2 class="m-xs" id="saldodinheiro"></h2>

                                <small>Saldo Dinheiro</small>
                            </div>
                        </div>
                    </div>
                    <div class="col-xs-4 col-lg-4 p-w-xs pointer" onclick="window.location.href='@Url.Action("Index", "Lancamento")'">
                        <div class="width100 bloco widget blue-bg p-md text-center">
                            <div class="m-b-xs">
                                <i class="m-b-sm far fa-money-bill-alt fa-3x"></i>
                                <h2 class="m-xs" id="saldo"></h2>

                                <small>Saldo Geral</small>
                            </div>
                        </div>
                    </div>
                }
            </div>
            <div class="row">
                <div class="pointer" onclick="window.location.href='@Url.Action("Index", "Participante")'">
                    <div class="col-xs-12 p-w-xs">
                        <div class="widget-head-color-box lazur-bg p-lg text-center">
                            <div class="m-b-md">
                                <h2 class="font-bold no-margins">
                                    Últimos Inscritos
                                </h2>
                            </div>
                        </div>
                        <div class="widget-text-box">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>Nome</th>
                                        <th>Idade</th>
                                    </tr>
                                </thead>
                                <tbody id="ultimos-inscritos"></tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-6 col-xs-12 p-w-xs">
            <div class="pointer">
                <div class="widget-head-color-box black-bg p-lg text-center">
                    <div class="m-b-md">
                        <h2 class="font-bold no-margins">
                            Equipes
                        </h2>
                    </div>

                    <div style="display:flex">
                        <div style="display:flex; margin:auto">
                            <i class="m-b-sm fa fa-female fa-2x m-r-xs" style="color: white !important; margin-top: auto; margin-bottom: auto"></i>
                            <span class="m-r-lg" style="margin-top:auto;margin-bottom:auto" id="equipe-female">32</span>
                            <i class="m-b-sm fa fa-male fa-2x m-r-xs" style="color: white !important; margin-top: auto; margin-bottom: auto"></i>
                            <span class="m-r-lg" style="margin-top:auto;margin-bottom:auto" id="equipe-male">32</span>
                            <i onclick="getEquipantesExcel()" class="m-b-sm fa fa-file-excel fa-2x m-r-xs" style="color: white !important; margin-top: auto; margin-bottom: auto"></i>
                    
                        </div>
                    </div>
                    </div>
                <div class="widget-text-box">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Equipe</th>
                                <th>Membros</th>
                            </tr>
                        </thead>
                        <tbody id="tb-equipes"></tbody>
                        <tfoot>
                            <tr>
                                <th>Total</th>
                                <th id="totalEquipe"></th>
                            </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
            <div class="pointer" onclick="window.location.href='@Url.Action("Index", "Reuniao")'">
                <div class="widget-head-color-box blue-bg p-lg text-center">
                    <div class="m-b-md">
                        <h2 class="font-bold no-margins">
                            Reuniões
                        </h2>
                    </div>
                </div>
                <div class="widget-text-box">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Reunião</th>
                                <th>Presentes</th>
                            </tr>
                        </thead>
                        <tbody id="tb-reunioes"></tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <div class="row detalhamento-equipes">
        <div class="col-lg-12 col-xs-12">
            <div class="widget-head-color-box black-bg p-lg text-center">
                <div class="m-b-md">
                    <h2 class="font-bold no-margins">
                        Detalhamento das Equipes
                    </h2>
                </div>
            </div>
            <div class="widget-text-box">
                <table class="table">
                    <thead>
                        <tr>
                            <th>Nome</th>
                            <th>Fone</th>
                        </tr>
                    </thead>
                    <tbody id="tb-detalhamento-equipes">
                        

                    </tbody>                    
                </table>
            </div>
        </div>
    </div>
</div>


@section Styles {
    <style>
        .bloco {
            max-height: 160px;
        }
    </style>
}

@section Scripts {

    <script src="~/Scripts/app/Home/admin.js?@ViewBag.Numero"></script>

    <script>

    </script>
}